import { TransactionPayload } from "@/types/transaction";

export const INITIAL_TRANSACTIONS: TransactionPayload[] = [
  {
    id: "tx-2026-0901",
    payeeName: "Helios Quantum Technologies Ltd.",
    targetAccount: {
      accountNumber: "882-9410-4491",
      routingNumber: "DBSSSGSGXXX",
      bankName: "DBS Bank Singapore",
      swiftBic: "DBSSSGSG",
      country: "Singapore",
    },
    amount: 485000,
    currency: "USD",
    justification: "Urgent hardware acquisition prepayment requested via urgent video conference with purported CEO.",
    urgency: "CRITICAL",
    reportedChannel: "DEEPFAKE_VIDEO_CALL",
    initiator: {
      name: "Marcus Vance",
      email: "m.vance@enterprise-corp.com",
      department: "Treasury & Global Payments",
    },
    payloadHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    status: "PENDING_AUTHORIZATION",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(), // 12 mins ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "tx-2026-0894",
    payeeName: "Azure Cloud Core Infrastructure Ltd.",
    targetAccount: {
      accountNumber: "4092-1829-4481-9920",
      routingNumber: "021000021",
      bankName: "JPMorgan Chase Bank, N.A.",
      swiftBic: "CHASUS33",
      country: "United States",
    },
    amount: 1250000,
    currency: "USD",
    justification: "Annual enterprise cloud hosting cluster expansion per Q3 committed purchase order PO-8819.",
    urgency: "HIGH",
    reportedChannel: "ROUTINE_INVOICE_PROCEDURE",
    initiator: {
      name: "Elena Rostova",
      email: "e.rostova@enterprise-corp.com",
      department: "Cloud Operations Finance",
    },
    payloadHash: "4a5c68b912e73f8d20911a3b5c7e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e",
    status: "CRYPTOGRAPHICALLY_AUTHORIZED",
    createdAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    authProof: {
      credentialId: "cred_ES256_Enclave_TouchID_8921",
      rawSignature: "MEUCIQDf82yV91jQ1bXNnJkl3mP8rTvW4xY0zA7bC9dE1fGh2wIgU5kLmNoPqRsTuVwXyZ0123456789AbCdEfGhIjKlMn",
      authenticatorData: "SZYN5YgOjGh0NBd2YFvksq6ihtPCmFwv87qDHTYwBQUAAAAA",
      clientDataJSON: "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiU2lnbmVkUGF5bG9hZDIwMjYiLCJvcmlnaW4iOiJodHRwczovL2ludGVybmFsLW9vYi5wb3J0YWwifQ",
      signatureAlgorithm: "ES256 (NIST P-256 + ECDSA)",
      userVerified: true,
      userPresent: true,
      approvedAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
      approverEmail: "cfo@enterprise-corp.com",
      authenticatorType: "Apple Secure Enclave (TouchID / FaceID)",
      challengeSigned: "4a5c68b912e73f8d20911a3b5c7e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e",
    },
  },
  {
    id: "tx-2026-0889",
    payeeName: "Apex Capital Liquidity Holdings Ltd.",
    targetAccount: {
      accountNumber: "KY09-BARC-2009-8831-9210",
      routingNumber: "BARCKYGGXXX",
      bankName: "Barclays Bank Cayman",
      swiftBic: "BARCKYGG",
      country: "Cayman Islands",
    },
    amount: 890000,
    currency: "USD",
    justification: "Confidential acquisition escrow funding request purportedly received from CEO during urgent phone call.",
    urgency: "CRITICAL",
    reportedChannel: "VOICE_CLONE_PHONE",
    initiator: {
      name: "Marcus Vance",
      email: "m.vance@enterprise-corp.com",
      department: "Treasury & Global Payments",
    },
    payloadHash: "9f8e7d6c5b4a3928170f1e2d3c4b5a69788796a5b4c3d2e1f0a9b8c7d6e5f4a3",
    status: "FLAGGED_AS_FRAUD",
    createdAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 312).toISOString(),
    fraudReport: {
      flaggedAt: new Date(Date.now() - 1000 * 60 * 312).toISOString(),
      flaggedBy: "ceo@enterprise-corp.com",
      reason: "Synthetic Voice Clone Impersonation Detected",
      details: "Executive verified they never authorized this wire transfer nor placed the telephone call. Impersonator used AI audio clone of CEO's voice.",
      suspectedChannel: "VOICE_CLONE_PHONE",
    },
  },
];
